name: plate_number
description: " A Flutter package for capturing and displaying vehicle plate numbers."
version: 0.1.0
homepage: https://github.com/ArAdBey/plate-number

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  bloc: ^9.2.1
  country_flags: ^4.1.2
  flutter_svg: ^2.0.0
  args: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/de_inspection_sticker.png
    - assets/de_state_seal.png
    - assets/flags/Flag_of_Iran.svg
